### ISSUE TITLE
where can I get a develop document?

### ISSUE THREAD

**Issue by fatcat22** [inklabsfoundation/inkchain#121]
Is there any dev document I can refer to? I mainly want to know how to run this program on my system without docker.

tks.

**Comment by qiang0723** [comment]
1. If you want to dev a smart contract, you can refer to this `https://baas.zhigui.com/technical_document`.  
2. Now we recommend using docker as the runtime environment. But if you want to run without docker, First you should very familiar with system components and operating principles,  reference image generation file(/images) and running file(/examples/cli_test/docker-compose-2org-4peer-solo.yaml), and then use the script to simulate a running environment for Peer, Orderer and CA. 
PS: Related scripts are already in our submission plan.

**Comment by fatcat22** [comment]
Thanks for reply. I'll try it.
