### ISSUE TITLE
What version of Hyperledger Fabric was this code forked from?

### ISSUE THREAD

**Issue by bryanedds** [inklabsfoundation/inkchain#125]
Hi!

My team is studying your code base for potential contribution. We were wondering what version of Hyperledger Fabric you forked this from? We're guessing version 1.1 or 1.2, but we can't tell for sure because it looks like there was some work done on the code even before the first commit in this repo.

Thank you very much for your time!

**Comment by GrapeBaBa** [comment]
@bryanedds The code is based fabric 1.0.x.

**Comment by bryanedds** [comment]
Thank you kindly for your assistance!
