### ISSUE TITLE
copy code from others?

### ISSUE THREAD

**Issue by ampm** [inklabsfoundation/inkchain#62]
删掉的是INK copy的代码？
![image](https://user-images.githubusercontent.com/1634096/37501046-8121ba10-2907-11e8-9003-5df1e3160217.png)
建议INK把用的开源东西也列出来吧，然后给其他做区块链的做个榜样，体面。

**Comment by lafenicecc** [comment]
您好，这里是ERC20标准对应的相关合约。由于Qtum支持以太坊虚拟机（EVM），所以Qtum的token通常也采用该标准合约。INK这部分工作的关键在于支持INK联盟链和Qtum/Ethereum的跨链交互，所以引入ERC20作为examples。
INK联盟链还遵循了Hyperledger Fabric标准，详细改进设计可见白皮书；联盟链部署项目用到了Kubernetes。这些都在文档中有明确体现。

**Comment by lafenicecc** [comment]
欢迎试用BaaS体验相关功能，https://baas.ink.plus/
INK中的一部分设计和实现也在不断回馈Hyperledger Fabric和Cello项目。之后会有更多Feature启动，包括对Orderer Service共识机制的改进等。

**Comment by wangh09** [comment]
Please notice that the public-chain side of INK-ETH cross-chain protocol is based on the ERC20 contract, which is what you are talking about. This is well described in the white paper and the documentation : )
