### ISSUE TITLE
Cross-chain transfer interface

### ISSUE THREAD

**Issue by AlpherJang** [inklabsfoundation/inkchain#63]
Enabling asset transfer between inkchain and another public blockchain.
Ethereum and Qtum would be the start.

**Comment by lafenicecc** [comment]
Please set more sub-tasks, including both public chain side (contract) and consortium chain side (chain and contract). Detailed documentations are needed as well.

**Comment by AlpherJang** [comment]
- public chain side need a smart contract provides these features:
   - lock the number of INK coins transferred from user
   - transfer the number of INK coins from contract to user
   - validate the signature strings from consortium chain side
- consortium chain side need a chaincode provides these features:
   - issue the number of INK coins from INK issue account
   - request public chain node to validate the turn out transaction has confirmed
  - endoser sign the transaction‘s args
